/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JDicomParse;

import JDicomParse.ApplyParse;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
